version: 2

sources:

  - name: RAW
    tables:
      - name: raw_sales
        identifiers: raw_sales

  - name: DEV_STATIC
    tables:
      - name: state_lookup
        identifier: state_lookup

      - name: city_names
        identifier: city_names
