USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS dbt
PASSWORD = 'xxxx'
LOGIN_NAME = 'DBT'
MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = 'COMPUTE_WH'
DEFAULT_ROLE = 'TRANSFORM'
DEFAULT_NAMESPACE = 'AMAZON.RAW'
COMMENT = 'DBT user used for data transformation';
GRANT ROLE TRANSFORM TO USER DBT;

CREATE DATABASE IF NOT EXISTS AMAZON;
CREATE SCHEMA IF NOT EXISTS AMAZON.RAW;

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE AMAZON TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE AMAZON TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AMAZON TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA AMAZON.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA AMAZON.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES in DATABASE AMAZON TO ROLE TRANSFORM;
